import { getServerSession } from "next-auth";
import Nav from "./Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  return (
    <html lang="ko">
      <body className={inter.className}>
        {session ? (
          <div className="wrap">
            <Nav name={session.user.name} />
            {children}
          </div>
        ) : (
          <div>{children}</div>
        )}
      </body>
    </html>
  );
}
